version: "3.9"
services:
  server:
    build:  ./backend
    ports: 
    - "5000:5000"
    volumes: 
    - ./backend/
    environment: 
      FLASK_ENV: development
  web:
    build: ./client
    ports: 
      - "3000:3000"
    volumes: 
      - ./client/src/app
    depends_on: 
      - server